version: '3'
 
services:
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    container_name: reactadmin_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - "reactadmin_dbdata:/var/lib/mysql"
      - "./app_db.sql:/docker-entrypoint-initdb.d/app_db.sql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: reactadmin_pma
    links:
      - db
    environment:
      PMA_HOST: reactadmin_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  web:
    image: reactadmin_net:1.0
    container_name: reactadmin_net
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - 8082:80
volumes:
  reactadmin_dbdata: